import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import PublicHeader from "@/app/(public)/PublicHeader";
import Footer from "@/components/layout/Footer";
import { isUserLoggedIn } from "@/util/userUtil";
import AppHeader from "../(app)/AppHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isLoggedIn = await isUserLoggedIn();

  return (
    <div
      className={`bg-bg-primary min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      {isLoggedIn ? <AppHeader /> : <PublicHeader />}
      {children}
      <Footer />
    </div>
  );
}
